# vim:ft=ansible:
---
- include: preparehost.yml

- name: Deploy home assistant cofig
  template:
    src: hass-configuration.yaml.j2
    dest: "{{ docker_host_workdir }}/config/configuration.yaml"
    owner: root
    group: root
    mode: 0644
  when:
    - hass_deploy_config == True

- name: Deploy docker container
  docker_container:
    name: "{{ hass_container_name }}"
    image: "{{ hass_image_name }}"
    state: "{{ hass_container_state }}"
    # restart: yes
    restart_policy: "{{ hass_container_restart_policy }}"
    pull: "{{ hass_image_pull }}"
    ports:
      - "{{ hass_container_listen_port }}:{{ hass_cfg_base_url_port }}"
    volumes:
      - "{{ docker_host_workdir }}/config/:/config"
      - "/etc/letsencrypt/live/{{ hass_cfg_base_url }}/:/etc/letsencrypt/live/{{ hass_cfg_base_url }}"

- name: Hass device tracker platform
  template:
    src: device_tracker.yaml.j2
    dest: "{{ docker_host_workdir }}/config/components.d/device_tracker.yaml"
    owner: root
    group: root
    mode: 0644
  when:
    - hass_cfg_device_tracker_platform != ""


# /usr/bin/python3 -m homeassistant --script check_config --config /config
